#!/bin/sh
set -e

cd "$(dirname "$0")"

DOCKER_VOLUME="-v `pwd`:/app"
DOCKER_IMAGE="periodic-gc-dev"

DOCKER_BUILDKIT=1 docker build -t ${DOCKER_IMAGE} -f Dockerfile .
docker run --rm -it ${DOCKER_VOLUME} ${DOCKER_IMAGE}
