#!/bin/sh
time -v out/idle-gc-bench
time -v out/idle-gc-bench --sync-every
time -v out/idle-gc-bench --background-every
time -v out/idle-gc-bench --start --poll=0.1
time -v out/idle-gc-bench --start --poll=0.1 --force=0.1
time -v out/idle-gc-bench --start --force=0.1
time -v out/idle-gc-bench --start --poll=0.1 --sync-every
time -v out/idle-gc-bench --start --poll=0.1 --background-every
time -v out/idle-gc-bench --start --poll=0.1 --request-limit=2
